name: WayWay Local Environment
values:
  - key: base_url
    value: 'http://127.0.0.1:8000'
  - key: wisatawan_email
    value: wisatawan@test.com
  - key: wisatawan_password
    value: Password123
  - key: admin_email
    value: admin@wayway.com
  - key: admin_password
    value: Password123
  - key: pemilik_email
    value: pemilik@test.com
  - key: pemilik_password
    value: Password123
  - key: travel_agent_email
    value: agent@test.com
  - key: travel_agent_password
    value: Password123
  - key: csrf_token
    value: ''
  - key: waybot_session_token
    value: ''
  - key: destinasi_id
    value: '1'
  - key: kategori_id
    value: '1'
  - key: paket_id
    value: '2'
  - key: transaksi_id
    value: '1'
  - key: edit_request_id
    value: '1'
  - key: itinerary_history_id
    value: '1'
  - key: travel_package_id
    value: '1'
  - key: subscription_package_id
    value: '1'
  - key: midtrans_server_key
    value: YOUR_MIDTRANS_SERVER_KEY
  - key: midtrans_client_key
    value: YOUR_MIDTRANS_CLIENT_KEY
  - key: midtrans_signature
    value: ''
  - key: user_lat
    value: '1.1296758'
  - key: user_lng
    value: '104.0452254'
  - key: app_name
    value: WayWay
  - key: app_env
    value: local
